config/routes.rb
Rails.application.routes.draw do
  get 'divisions/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  get "home", to: "pages#home"
  get "about", to: "pages#about"
  
  # get "titles", to: "titles#index"
  resources :titles
  resources :divisions
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :title

  validates :title_id, presence: true, uniqueness: true
end

app/models/title.rb
class Title < ApplicationRecord
  has_one :division

  validates :name, presence: true, length: {minimum: 2}, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  def index
    @page = {
      nav_divisions: 'active'
    }
    @divisions = Title.joins(:divisions).all
  end

  def show
    @page = {
      nav_divisions: 'active'
    }
    @division = Division.find(params[:id])
  end

  def new
    @page = {
      nav_divisions: 'active'
    }
    @_content = 'Add new Division.';
    @division = Division.new
  end

  def create
    @page = {
      nav_divisions: 'active'
    }
    # render plain: params[:division].inspect
    @division = Division.new(division_params);
    if(@division.save)
      redirect_to @division
    else
      render 'new'
    end
  end

  private
  def division_params
    params.require(:division).permit(:title_id, :full_title, :tag)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @page = {
      nav_about: 'active'
    }
    @_title = 'About Page';
    @_content = 'It is about us page.';
  end

  def home
    @page = {
      nav_home: 'active'
    }
    @_title = 'Home Page';
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def index
    @page = {
      nav_titles: 'active'
    }
    @titles = Title.all
  end

  def show
    @page = {
      nav_titles: 'active'
    }
    @title = Title.find(params[:id])
  end

  def new
    @page = {
      nav_titles: 'active'
    }
    @_content = 'Add new Title.';
    @title = Title.new
  end

  def create
    @page = {
      nav_titles: 'active'
    }
    # render plain: params[:title].inspect
    @title = Title.new(title_params);
    if(@title.save)
      redirect_to @title
    else
      render 'new'
    end
  end

  def edit
    @page = {
      nav_titles: 'active'
    }
    @_content = 'Edit this Title.';
    @title = Title.find(params[:id])
  end

  def update
    @page = {
      nav_titles: 'active'
    }
    @title = Title.find(params[:id])
    if(@title.update(title_params))
      redirect_to @title
    else
      render 'edit'
    end
  end

  def destroy
    @page = {
      nav_titles: 'active'
    }
    @title = Title.find(params[:id])
    @title.destroy
    redirect_to titles_path
  end
  
  private
  def title_params
    params.require(:title).permit(:name, :note, :tags)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/divisions/index.html.erb
<div>
  <table class="table table-hover table-sm">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">title_id</th>
        <th scope="col">title</th>
        <th scope="col">full_title</th>
        <th scope="col">tag</th>
        <th scope="col"><%= link_to 'Добавить', new_division_path %></th>
      </tr>
    </thead>
  
    <% @divisions.each do |division| %>
      <tr>
        <th scope="row"><%= division.id %></th>
        <td><%= division.title_id %></td>
        <td><%= division.search(1) %></td>
        <td class="text-muted"><i><%= division.full_title %></i></td>
        <td><%= division.tag %></td>
        <td><%= link_to 'Подробнее', division_path(division) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/divisions/new.html.erb
<div>
  <p><%= @_content %></p>
</div>
<div>
  <%= form_with scope: :division, url: divisions_path, local: true do |form| %>
  <% if @division.errors.any? %>
    <% @division.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= form.label :title_id %><br>
    <%= form.text_field(:title_id, {class: "form-control"}) %>
  </p>
 
  <p>
    <%= form.label :full_title %><br>
    <%= form.text_area(:full_title, {class: "form-control"}) %>
  </p>
  <p>
    <%= form.label :tag %><br>
    <%= form.text_area(:tag, {class: "form-control"}) %>
  </p>
  <p>
    <%= form.submit('Сохранить', {class: "btn btn-primary"}) %>
  </p>
<% end %>
</div>

app/views/divisions/show.html.erb
<div class="container">
  <br>
  <div class="card">
    <div class="card-body">
      <h5 class="card-division"><%= @division.title_id %></h5>
      <p class="card-text"><%= @division.full_title %></p>
      <small class="text-muted"><%= @division.tag %></small>
    </div>
    <div class="card-footer">
      <div class="row justify-content-between">
        <div class="btn-group btn-group-sm col-3" role="group">
          <%= link_to "Изменить", edit_division_path(@division.id),
            class: "btn btn-outline-warning col-6" %>
          <%= link_to "Удалить", division_path(@division.id),
            class: "btn btn-outline-danger col-6",
            method: :delete,
            data: {confirm: "Вы намерены удалить '#{@division.id} #{@division.full_title}'?" } %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
			<button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<%= link_to 'Home', home_path, class: "nav-link #{@page[:nav_home]}" %>
					</li>
					<li class="nav-item">
						<%= link_to 'Titles', titles_path, class: "nav-link #{@page[:nav_titles]}" %>
					</li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle <%= @page[:nav_divisions] %>"
              data-toggle="dropdown" href="/divisions" role="button"
              aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu">
              <%= link_to 'Добавить', new_division_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Показать все', divisions_path, class: "dropdown-item" %>
            </div>
          </li>
					<li class="nav-item">
						<%= link_to 'About', about_path, class: "nav-link #{@page[:nav_about]}" %>
					</li>
				</ul>
				<form class="form-inline my-2 my-lg-0" action="https://www.google.com/search?" method="get">
    			<input class="form-control mr-sm-2" type="text" name="q" placeholder="Search" aria-label="Search">
    			<button class="btn btn-outline-secondary my-2 my-sm-0" type="submit" value="search">Search</button>
    		</form>
			</div>
		</nav>
      <div class="container">
      	<%= yield %>
			</div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @_title %></h1>
<p><%= @_content %></p>

app/views/pages/home.html.erb
<h1><%= @_title %></h1>

app/views/titles/edit.html.erb
<div>
  <p><%= @_content %></p>
</div>
<div>
  <%= form_with scope: :title, url: title_path(@title), method: :patch, local: true do |form| %>
  <% if @title.errors.any? %>
    <% @title.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field(:name, {class: "form-control"}) %>
  </p>
 
  <p>
    <%= form.label :note %><br>
    <%= form.text_area(:note, {class: "form-control"}) %>
  </p>
  <p>
    <%= form.label :tags %><br>
    <%= form.text_area(:tags, {class: "form-control"}) %>
  </p>
  <p>
    <%= form.submit("Сохранить", {class: "btn btn-primary"}) %>
  </p>
<% end %>
</div>

app/views/titles/index.html.erb
<div>
  <table class="table table-hover table-sm">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Titles</th>
        <th scope="col">Tags</th>
        <th scope="col">Notations</th>
        <th scope="col"><%= link_to 'New', new_title_path %></th>
      </tr>
    </thead>
  
    <% @titles.each do |title| %>
    <tr>
      <th scope="row"><%= title.id %></th>
      <td><%= title.name %></td>
      <td class="text-muted"><i><%= title.tags %></i></td>
      <td><%= title.note %></td>
      <td><%= link_to 'Show', title_path(title) %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/titles/new.html.erb
<div>
  <p><%= @_content %></p>
</div>
<div>
  <%= form_with scope: :title, url: titles_path, local: true do |form| %>
  <% if @title.errors.any? %>
    <% @title.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field(:name, {class: "form-control"}) %>
  </p>
 
  <p>
    <%= form.label :note %><br>
    <%= form.text_area(:note, {class: "form-control"}) %>
  </p>
  <p>
    <%= form.label :tags %><br>
    <%= form.text_area(:tags, {class: "form-control"}) %>
  </p>
  <p>
    <%= form.submit('Сохранить', {class: "btn btn-primary"}) %>
  </p>
<% end %>
</div>

app/views/titles/show.html.erb
<div class="container">
  <br>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @title.name %></h5>
      <p class="card-text"><%= @title.note %></p>
      <small class="text-muted"><%= @title.tags %></small>
    </div>
    <div class="card-footer">
      <div class="row justify-content-between">
        <div class="btn-group btn-group-sm col-3" role="group">
          <%= link_to "Изменить", edit_title_path(@title.id),
            class: "btn btn-outline-warning col-6" %>
          <%= link_to "Удалить", title_path(@title.id),
            class: "btn btn-outline-danger col-6",
            method: :delete,
            data: {confirm: "Вы намерены удалить '#{@title.name}'?" } %>
        </div>
      </div>
    </div>
  </div>